### ISSUE TITLE
No menu icon, not running?

### ISSUE THREAD

**Issue by onewheeltom** [DaltonLens/DaltonLens#1]
Running on 27 in mid 2011 iMac, os x 10.12.6. Launch DaltonLens, does not appear to start and no icon in menu bar. Not in process list.

**Comment by Waitsnake** [comment]
I'm not the author of this software, but as far as I see in the source code it uses Metal API to render and not OpenGL API. The Metal API support starts with Macs older as Mid 2012 (except Mac Pro models from Mid 2010 with supported graphics cards). Since your Mac is from 2011 it only supports OpenGL API and will probably not run this program. I would be nice if the program at least opens a dialog box to inform the user about this problem.

**Comment by nburrus** [comment]
DaltonLens does not use Metal anymore as I'm working on making it cross-platform, so the new versions might work on older mac. Otherwise I agree that checking if Metal is supported would have been ideal, although I'll probably just bump the deployment requirements as I don't have the resource to test on very old machines.
